# Generated by Django 4.2.7 on 2023-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rehearsal_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
